### ISSUE TITLE
Great job! Would you plan to open the data access?

### ISSUE THREAD

**Issue by chenxinli001** [Weixiang-Sun/Bora#1]

**Comment by Weixiang-Sun** [comment]
Ofc, the dataset is in processing, please send me an email with your WeChat to contact and share.

**Comment by PKUHaoWang** [comment]
> Ofc, the dataset is in processing, please send me an email with your WeChat to contact and share.

Hi, could you please share the dataset with me? Thanks a lot!

**Comment by Weixiang-Sun** [comment]
Our data v1 will be uploaded next week. Sorry for long time waiting.
